import { GalleryGrid } from './Gallery'
import type { GalleryImage } from './Gallery'
import { BrandingSettings } from './BrandingSettings'
import { createContext, useContext, useState, useEffect } from 'react'
import { Link, NavLink, Navigate, Outlet, useNavigate, useParams } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Activity, ArrowUpRight, BarChart3, Bell, CalendarDays, ClipboardList, FileText, Image, LayoutDashboard, LogOut, Mail, Plus, Search, Settings, ShieldCheck, Stethoscope, Users, X } from 'lucide-react'
import { addDays, api, ApiError, dateText, label, statuses, timeText, today, transitions, useServices } from './lib'
import type { Appointment, Paginated, User } from './lib'
import { Badge, Empty, ErrorBox, Loading, Logo, Seo } from './components'
import { SlotPicker } from './Booking'

const UserContext=createContext<User|null>(null)
const useStaff=()=>useContext(UserContext)!
export function Login() {
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false);const navigate=useNavigate();const cache=useQueryClient()
  return <div className="login-page"><Seo title="Staff sign in" noindex/><div className="login-card"><Logo/><span className="eyebrow">CLINIC WORKSPACE</span><h1>Welcome back.</h1><p>Sign in to manage your clinic’s day.</p><ErrorBox error={error}/><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('/auth/login','POST',{email,password});await cache.invalidateQueries({queryKey:['me']});navigate('/admin',{replace:true})}catch(err){setError(err)}finally{setBusy(false)}}}><label>Email address<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="button full" disabled={busy}>{busy?'Signing in…':'Sign in'}<ArrowUpRight size={18}/></button></form><p className="small-text">Accounts are created by your clinic administrator.</p><Link className="text-link" to="/">← Back to the website</Link></div></div>
}
const nav=[['','Overview',LayoutDashboard,'all'],['appointments','Appointments',CalendarDays,'all'],['patients','Patients & contacts',Users,'staff'],['services','Services',Stethoscope,'admin'],['availability','Availability',CalendarDays,'admin'],['closures','Closures & breaks',CalendarDays,'admin'],['enquiries','Enquiries',Mail,'staff'],['content','Pages & articles',FileText,'admin'],['banners','Banners',FileText,'admin'],['redirects','Redirects',ArrowUpRight,'admin'],['media','Media library',Image,'admin'],['testimonials','Testimonials',Activity,'admin'],['reports','Reports',BarChart3,'admin'],['notifications','Notifications',Bell,'admin'],['users','Users & roles',Users,'admin'],['settings','Settings',Settings,'admin'],['audit','Audit log',ShieldCheck,'admin']] as const
export function AdminLayout() {
  const query=useQuery({queryKey:['me'],queryFn:()=>api<User>('/auth/me'),retry:false});const cache=useQueryClient();const navigate=useNavigate();const [logoutError,setLogoutError]=useState<unknown>()
  if(query.isPending)return <Loading/>;if(query.error){if(query.error instanceof ApiError&&query.error.status===401)return <Navigate to="/login" replace/>;return <ErrorBox error={query.error}/>}
  const user=query.data!;const allowed=(role:string)=>role==='all'||user.role==='admin'||(role==='staff'&&user.role==='receptionist')
  return <UserContext.Provider value={user}><div className="admin-shell"><aside className="sidebar"><Logo/><span className="workspace-label">CLINIC WORKSPACE</span><nav aria-label="Staff navigation">{nav.filter(n=>allowed(n[3])).map(([path,name,Icon])=><NavLink key={path} to={`/admin${path?'/'+path:''}`} end><Icon size={18}/>{name}</NavLink>)}</nav><div className="staff-profile"><span className="avatar">{user.name.slice(0,1)}</span><span><strong>{user.name}</strong><small>{label(user.role)}</small></span><button className="icon-button" aria-label="Sign out" onClick={async()=>{try{await api('/auth/logout','POST');cache.clear();navigate('/login')}catch(e){setLogoutError(e)}}}><LogOut size={18}/></button></div></aside><div className="admin-main"><header className="admin-topbar"><span><span className="little-dot"/> Nav Jeevan Chikitsalay</span><Link to="/" className="text-link">View website <ArrowUpRight size={16}/></Link></header><div className="admin-content"><Seo title="Clinic workspace" noindex/><ErrorBox error={logoutError}/><Outlet/></div></div></div></UserContext.Provider>
}
export function AdminHeading({title,subtitle,action}:{title:string;subtitle:string;action?:React.ReactNode}) {return <div className="admin-heading"><div><span className="eyebrow">NAV JEEVAN · WORKSPACE</span><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>}
export function Dashboard() {
  const user=useStaff();const {data,isPending,error}=useQuery({queryKey:['admin','dashboard'],queryFn:()=>api<{today:string;counts:Record<string,number>;total:number;appointments:Appointment[];new_enquiries:number}>('/admin/dashboard'),refetchInterval:30000})
  return <><AdminHeading title={`Hello, ${user.name.split(' ')[0]}.`} subtitle="Here’s what’s happening at your clinic today." action={user.role!=='doctor'&&<Link className="button" to="/admin/book"><Plus size={17}/>New appointment</Link>}/><ErrorBox error={error}/>{isPending?<Loading/>:data&&<><div className="stats-grid">{([['Today’s appointments',data.total,CalendarDays],['Pending approval',data.counts.pending||0,ClipboardList],['Completed visits',data.counts.completed||0,CheckIcon],['New enquiries',data.new_enquiries,Mail]] as const).map(([title,value,Icon])=><div className="stat-card" key={String(title)}><div><span>{String(title)}</span><strong>{String(value)}</strong></div><Icon size={22}/></div>)}</div><div className="card"><div className="section-heading"><div><h2>Today’s schedule</h2><p>{dateText(data.today+'T12:00:00+05:30')}</p></div><Link className="text-link" to="/admin/appointments">View all <ArrowUpRight size={17}/></Link></div><AppointmentTable rows={data.appointments}/></div><div className="admin-bottom-grid"><div className="card"><span className="eyebrow">APPOINTMENT FLOW</span><h3>A clear path through each visit</h3><div className="status-flow"><Badge status="pending"/>→<Badge status="confirmed"/>→<Badge status="checked_in"/>→<Badge status="completed"/></div><p>Status changes are recorded in the appointment history.</p></div><div className="card pale"><h3>Keep your clinic up to date</h3><p>Review today’s schedule and make sure your public information is accurate.</p>{user.role==='admin'&&<Link to="/admin/settings" className="text-link">Review clinic settings <ArrowRightIcon/></Link>}</div></div></>}</>
}
function CheckIcon({size=22}:{size?:number}){return <ShieldCheck size={size}/>}
function ArrowRightIcon(){return <ArrowUpRight size={17}/>}
function AppointmentTable({rows}:{rows:Appointment[]}) {return !rows.length?<Empty>No appointments in this view.</Empty>:<div className="table-scroll"><table><thead><tr><th>Patient</th><th>Appointment</th><th>Consultation</th><th>Status</th><th>Source</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td><strong>{a.patient.name}</strong><small>{a.patient.phone}</small></td><td><strong>{timeText(a.starts_at)}</strong><small>{dateText(a.starts_at)}</small></td><td>{a.service.name}<small>{a.reference}</small></td><td><Badge status={a.status}/></td><td>{label(a.source)}</td><td><Link className="text-link" to={`/admin/appointments/${a.id}`}>Open <ArrowUpRight size={15}/></Link></td></tr>)}</tbody></table></div>}
function Filters({filters,setFilters}:{filters:Record<string,string>;setFilters:(v:Record<string,string>)=>void}) {const services=useServices();return <div className="filters"><label>From<input type="date" value={filters.from||''} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>To<input type="date" value={filters.to||''} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><label>Status<select value={filters.status||''} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Service<select value={filters.service_id||''} onChange={e=>setFilters({...filters,service_id:e.target.value})}><option value="">All services</option>{services.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Source<select value={filters.source||''} onChange={e=>setFilters({...filters,source:e.target.value})}><option value="">All sources</option>{['website','phone','walk_in'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label></div>}
const queryString=(filters:Record<string,string>)=>new URLSearchParams(Object.entries(filters).filter(([,v])=>v)).toString()
export function Appointments() {
  const user=useStaff();const [filters,setFilters]=useState<Record<string,string>>({from:today(),to:today()});const [page,setPage]=useState(1);const [view,setView]=useState('list');const [search,setSearch]=useState('');const query=useQuery({queryKey:['admin','appointments',filters,page],queryFn:()=>api<Paginated<Appointment>>(`/admin/appointments?${queryString(filters)}&page=${page}`)});const set=(v:Record<string,string>)=>{setPage(1);setFilters(v)}
  return <><AdminHeading title="Appointments" subtitle="Manage requests, arrivals, and the day’s visits." action={user.role!=='doctor'&&<Link to="/admin/book" className="button"><Plus size={17}/>New appointment</Link>}/><div className="card"><div className="list-toolbar"><form className="search" onSubmit={e=>{e.preventDefault();set({...filters,search})}}><Search size={18}/><input aria-label="Search appointments" placeholder="Search name, mobile or reference" value={search} onChange={e=>setSearch(e.target.value)}/><button className="button small secondary">Search</button></form><div className="segmented">{['list','day','week'].map(v=><button key={v} className={view===v?'active':''} onClick={()=>{setView(v);if(v==='day')set({...filters,from:today(),to:today()});if(v==='week')set({...filters,from:today(),to:addDays(today(),6)})}}>{label(v)}</button>)}</div></div><Filters filters={filters} setFilters={set}/><ErrorBox error={query.error}/>{query.isPending?<Loading/>:view==='list'?<AppointmentTable rows={query.data?.data||[]}/>:<div className="calendar-list">{Array.from(new Set(query.data?.data.map(a=>dateText(a.starts_at)))).map(day=><div key={day}><h3>{day}</h3>{query.data?.data.filter(a=>dateText(a.starts_at)===day).map(a=><Link to={`/admin/appointments/${a.id}`} className="calendar-event" key={a.id}><strong>{timeText(a.starts_at)}</strong><span>{a.patient.name}<small>{a.service.name}</small></span><Badge status={a.status}/></Link>)}</div>)}{!query.data?.data.length&&<Empty>No appointments in this view.</Empty>}</div>}<Pagination page={page} last={query.data?.last_page||1} setPage={setPage}/></div></>
}
function Pagination({page,last,setPage}:{page:number;last:number;setPage:(v:number)=>void}) {return <div className="pagination"><button className="button small secondary" disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {last}</span><button className="button small secondary" disabled={page>=last} onClick={()=>setPage(page+1)}>Next</button></div>}
export function AppointmentDetail() {
  const {id}=useParams();const user=useStaff();const cache=useQueryClient();const query=useQuery({queryKey:['admin','appointment',id],queryFn:()=>api<Appointment>(`/admin/appointments/${id}`)});const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false);const [date,setDate]=useState(addDays(today(),1));const [slot,setSlot]=useState('');const [mode,setMode]=useState('');const [notes,setNotes]=useState<string|null>(null);const [reason,setReason]=useState('')
  async function save(data:unknown){setBusy(true);try{setError(null);await api(`/admin/appointments/${id}/status`,'PATCH',data);await cache.invalidateQueries({queryKey:['admin']});cache.invalidateQueries({queryKey:['slots']});setMode('')}catch(e){setError(e)}finally{setBusy(false)}}
  if(query.isPending)return <Loading/>;if(query.error)return <ErrorBox error={query.error}/>;const a=query.data!
  return <><AdminHeading title={a.reference} subtitle={`${dateText(a.starts_at)} · ${timeText(a.starts_at)} IST`} action={<Badge status={a.status}/>}/><Link to="/admin/appointments" className="text-link">← All appointments</Link><ErrorBox error={error}/><div className="admin-bottom-grid"><div className="card"><h2>{a.patient.name}</h2><dl className="review-list"><div><dt>Mobile</dt><dd>{a.patient.phone}</dd></div><div><dt>Age group</dt><dd>{label(a.patient.age_group)}</dd></div><div><dt>Consultation</dt><dd>{a.service.name}</dd></div><div><dt>Source</dt><dd>{label(a.source)}</dd></div></dl><h3>Reason for visit</h3><p className="preserve-lines">{a.reason||'Not provided'}</p>{user.role!=='doctor'&&<><label>Internal reception notes<textarea value={notes??a.internal_notes??''} onChange={e=>setNotes(e.target.value)} rows={4}/></label><button className="button secondary" disabled={busy} onClick={()=>save({internal_notes:notes??a.internal_notes})}>Save notes</button><hr/><label>Change reason (optional)<input value={reason} onChange={e=>setReason(e.target.value)} maxLength={300}/></label><div className="form-actions wrap">{transitions[a.status]?.map(s=><button key={s} className="button secondary" disabled={busy} onClick={()=>s==='cancelled'?setMode('cancel'):save({status:s,change_reason:reason})}>{label(s)}</button>)}</div>{mode==='cancel'&&<div className="notice"><p>Cancel this appointment?</p><button className="button danger-button" disabled={busy} onClick={()=>save({status:'cancelled',change_reason:reason})}>Confirm cancellation</button><button className="button secondary" onClick={()=>setMode('')}>Keep</button></div>}{['pending','confirmed'].includes(a.status)&&<button className="text-link" onClick={()=>setMode('reschedule')}>Reschedule appointment</button>}{mode==='reschedule'&&<><SlotPicker serviceId={a.service_id} date={date} setDate={setDate} value={slot} onChange={setSlot}/><button className="button" disabled={!slot||busy} onClick={()=>save({starts_at:slot,change_reason:reason})}>Save new time</button></>}</>}</div><div className="card"><h2>Appointment history</h2><div className="timeline">{a.events?.map(e=><div key={e.id}><Badge status={e.to_status}/><p>{e.reason}</p><small>{dateText(e.created_at)} · {timeText(e.created_at)}</small></div>)}</div></div></div></>
}
type Row=Record<string,unknown>
type Field={key:string;label:string;type?:string;options?:string[];required?:boolean}
const definitions:Record<string,{title:string;description:string;fields:Field[];defaults:Row}>= {
 banners:{title:'Banners',description:'Published banners appear in a sliding carousel. Autoplay changes direction at each end; a single banner also slides. Unpublish to hide a banner.',defaults:{published:false},fields:[{key:'title',label:'Title',required:true},{key:'body',label:'Message',type:'textarea',required:true},{key:'link_label',label:'Link label'},{key:'link_path',label:'Local page path (e.g. /appointment)'},{key:'published',label:'Publish banner',type:'checkbox'}]},
 redirects:{title:'Redirects',description:'Redirect an old local URL to its new page. Permanent HTTP redirects are served by the built Laravel website.',defaults:{active:true},fields:[{key:'from_path',label:'Old path (e.g. /old-services)',required:true},{key:'to_path',label:'New path (e.g. /services)',required:true},{key:'active',label:'Active redirect',type:'checkbox'}]},
 services:{title:'Services',description:'Manage consultation options and publish approved descriptions.',defaults:{duration:20,icon:'stethoscope',published:false},fields:[{key:'name',label:'Name',required:true},{key:'slug',label:'URL slug',required:true},{key:'summary',label:'Short description',type:'textarea',required:true},{key:'description',label:'Full description',type:'textarea'},{key:'preparation',label:'Preparation guidance',type:'textarea'},{key:'duration',label:'Duration (minutes)',type:'number',required:true},{key:'seo_title',label:'SEO title'},{key:'seo_description',label:'SEO description'},{key:'published',label:'Publish this service',type:'checkbox'}]},
 availability:{title:'Availability',description:'Weekly booking windows in India Standard Time. Use separate windows for breaks.',defaults:{weekday:1,start_time:'09:00',end_time:'13:00',slot_minutes:20,buffer_minutes:0,capacity:1,active:true},fields:[{key:'weekday',label:'Weekday (0 Sunday – 6 Saturday)',type:'number',required:true},{key:'start_time',label:'Start time (IST)',type:'time',required:true},{key:'end_time',label:'End time (IST)',type:'time',required:true},{key:'slot_minutes',label:'Slot length (minutes)',type:'number',required:true},{key:'buffer_minutes',label:'Buffer between visits (minutes)',type:'number',required:true},{key:'capacity',label:'Patients per slot',type:'number',required:true},{key:'effective_from',label:'Effective from (optional)',type:'date'},{key:'effective_to',label:'Effective until (optional)',type:'date'},{key:'active',label:'Active',type:'checkbox'}]},
 closures:{title:'Closures & breaks',description:'Block holidays, doctor leave, or time away. Existing appointments remain visible for staff to reschedule.',defaults:{},fields:[{key:'starts_at',label:'Starts (IST)',type:'datetime-local',required:true},{key:'ends_at',label:'Ends (IST)',type:'datetime-local',required:true},{key:'reason',label:'Reason',required:true}]},
 content:{title:'Pages & articles',description:'Save drafts, preview your writing, and publish reviewed content.',defaults:{type:'article',language:'en',published:false},fields:[{key:'title',label:'Title',required:true},{key:'slug',label:'URL slug',required:true},{key:'type',label:'Content type',options:['article','faq','page']},{key:'language',label:'Language',options:['en','hi']},{key:'excerpt',label:'Excerpt',type:'textarea'},{key:'body',label:'Content (plain text)',type:'textarea',required:true},{key:'seo_title',label:'SEO title'},{key:'seo_description',label:'SEO description'},{key:'published',label:'Publish approved content',type:'checkbox'}]},
 enquiries:{title:'Enquiries',description:'Review incoming messages and track follow-up.',defaults:{status:'new'},fields:[{key:'status',label:'Status',options:['new','in_progress','converted','closed']},{key:'assigned_to',label:'Assigned staff user ID (optional)',type:'number'}]},
 testimonials:{title:'Testimonials',description:'Publish patient comments only with explicit consent.',defaults:{consent:false,published:false,sort_order:0},fields:[{key:'name',label:'Display name',required:true},{key:'quote',label:'Patient comment',type:'textarea',required:true},{key:'consent',label:'Explicit publication consent recorded',type:'checkbox'},{key:'published',label:'Publish',type:'checkbox'},{key:'sort_order',label:'Display order',type:'number',required:true}]},
 users:{title:'Users & roles',description:'Administrators manage the clinic. Reception manages visits. Doctors can view the schedule.',defaults:{role:'receptionist',active:true},fields:[{key:'name',label:'Name',required:true},{key:'email',label:'Email',type:'email',required:true},{key:'password',label:'Password (12+ characters; leave blank to keep)',type:'password'},{key:'role',label:'Role',options:['admin','receptionist','doctor']},{key:'active',label:'Account active',type:'checkbox'}]},
}
export function ResourcePage() {
  const {resource=''}=useParams();const user=useStaff();const definition=definitions[resource];const cache=useQueryClient();const [edit,setEdit]=useState<Row|null>(null);const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false);const [preview,setPreview]=useState(false);const [deleting,setDeleting]=useState<number|null>(null)
  const hasDialog=edit!==null||deleting!==null
  useEffect(()=>{if(!hasDialog)return;const dialog=document.querySelector<HTMLElement>('[role=dialog]');const previous=document.activeElement as HTMLElement|null;const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select,textarea,a[href]')||[]).filter(el=>el.offsetParent!==null);focusable()[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setEdit(null);setDeleting(null)}if(e.key==='Tab'){const items=focusable();const first=items[0];const last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus()}},[hasDialog])
  const allowed=!!definition&&(user.role==='admin'||(resource==='enquiries'&&user.role==='receptionist'))
  const query=useQuery({queryKey:['admin',resource],queryFn:()=>api<Row[]>(`/admin/${resource}`),enabled:allowed})
  if(!allowed)return <Empty>This section is not available for your role.</Empty>
  async function save(){if(!edit)return;setBusy(true);setError(null);const data={...edit};for(const field of definition.fields){if(field.type==='time')data[field.key]=String(data[field.key]||'').slice(0,5);if(field.type==='datetime-local'&&data[field.key])data[field.key]=String(data[field.key]).slice(0,16)+'+05:30';if(field.type==='number'&&data[field.key]==='')data[field.key]=null}try{await api(`/admin/${resource}${edit.id?'/'+edit.id:''}`,edit.id?'PUT':'POST',data);await cache.invalidateQueries({queryKey:['admin',resource]});cache.invalidateQueries({queryKey:['services']});cache.invalidateQueries({queryKey:['clinic']});cache.invalidateQueries({queryKey:['content']});setEdit(null)}catch(e){setError(e)}finally{setBusy(false)}}
  function open(row:Row){const data={...row};for(const field of definition.fields){if(field.type==='time')data[field.key]=String(data[field.key]||'').slice(0,5);if(field.type==='datetime-local'&&data[field.key]){const d=new Date(String(data[field.key]));data[field.key]=new Date(d.getTime()+330*60000).toISOString().slice(0,16)}}setEdit(data);setError(null);setPreview(false)}
  return <><AdminHeading title={definition.title} subtitle={definition.description} action={resource!=='enquiries'&&<button className="button" onClick={()=>open(definition.defaults)}><Plus size={17}/>Add new</button>}/><ErrorBox error={query.error}/>{query.isPending?<Loading/>:<div className="card">{!query.data?.length?<Empty>No records yet. Add your first one.</Empty>:<div className="table-scroll"><table><thead><tr><th>Record</th><th>Details</th><th>Status</th><th>Actions</th></tr></thead><tbody>{query.data?.map(row=><tr key={String(row.id)}><td><strong>{String(row.name||row.title||row.from_path||row.reason||(resource==='availability'?['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][Number(row.weekday)]:`#${row.id}`))}</strong><small>{String(row.slug||row.email||row.phone||'')}</small></td><td className="truncate">{resource==='availability'?`${String(row.start_time).slice(0,5)} – ${String(row.end_time).slice(0,5)} · capacity ${row.capacity}`:String(row.summary||row.to_path||row.message||row.quote||row.starts_at||row.type||row.role||'')}</td><td>{row.published!==undefined?<Badge status={row.published?'published':'draft'}/>:row.active!==undefined?<Badge status={row.active?'active':'inactive'}/>:String(row.status||'—')}</td><td><button className="text-link" onClick={()=>open(row)}>Edit</button>{!['users','enquiries'].includes(resource)&&<button className="text-link danger" onClick={()=>setDeleting(Number(row.id))}>Delete</button>}</td></tr>)}</tbody></table></div>}</div>}
    {deleting&&<div className="modal-backdrop"><div className="modal card" role="dialog" aria-modal="true" aria-label="Delete record"><h2>Delete this record?</h2><p>This removes the record. Services with bookings must be unpublished instead.</p><ErrorBox error={error}/><button className="button danger-button" disabled={busy} onClick={async()=>{setBusy(true);try{await api(`/admin/${resource}/${deleting}`,'DELETE');cache.invalidateQueries();setDeleting(null)}catch(e){setError(e)}finally{setBusy(false)}}}>Delete</button><button className="button secondary" onClick={()=>setDeleting(null)}>Keep record</button></div></div>}
    {edit&&<div className="modal-backdrop"><div className="modal card" role="dialog" aria-modal="true" aria-label="Edit record"><div className="section-heading"><h2>{edit.id?'Edit':'New'} {definition.title.toLowerCase()}</h2><button className="icon-button" aria-label="Close editor" onClick={()=>setEdit(null)}><X/></button></div><ErrorBox error={error}/>{resource==='enquiries'&&<div className="notice"><strong>{String(edit.name)} · {String(edit.phone)}</strong><p className="preserve-lines">{String(edit.message)}</p></div>}{preview?<div className="prose"><h2>{String(edit.title||edit.name||'')}</h2><p>{String(edit.excerpt||edit.summary||'')}</p><p className="preserve-lines">{String(edit.body||edit.description||'')}</p></div>:<form id="record-form" onSubmit={e=>{e.preventDefault();save()}}>{definition.fields.map(field=><DynamicField key={field.key} field={field} value={edit[field.key]} set={v=>setEdit({...edit,[field.key]:v})}/>)}</form>}<div className="form-actions">{['content','services'].includes(resource)&&<button className="button secondary" onClick={()=>setPreview(!preview)}>{preview?'Back to editing':'Preview'}</button>}{!preview&&<button className="button" type="submit" form="record-form" disabled={busy}>{busy?'Saving…':'Save changes'}</button>}</div></div></div>}</>
}
function DynamicField({field,value,set}:{field:Field;value:unknown;set:(value:unknown)=>void}) {const inputProps={required:field.required,value:String(value??''),onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>set(field.type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)};return <label className={field.type==='checkbox'?'checkbox':''}>{field.type==='checkbox'?<><input type="checkbox" checked={!!value} onChange={e=>set(e.target.checked)}/>{field.label}</>:<>{field.label}{field.options?<select {...inputProps}>{field.options.map(o=><option value={o} key={o}>{label(o)}</option>)}</select>:field.type==='textarea'?<textarea rows={field.key==='body'?10:3} {...inputProps}/>:<input type={field.type||'text'} {...inputProps}/>}</>}</label>}
export function Reports() {
  const [filters,setFilters]=useState<Record<string,string>>({from:addDays(today(),-30),to:today()});const user=useStaff();const query=useQuery({queryKey:['admin','report',filters],queryFn:()=>api<{total:number;statuses:Record<string,number>;sources:Record<string,number>;services:Record<string,number>;days:Record<string,number>;hours:Record<string,number>;enquiries:{status:string;total:number}[]}>(`/admin/reports/appointments?${queryString(filters)}`),enabled:user.role==='admin'})
  if(user.role!=='admin')return <Empty>Reports are available to administrators.</Empty>
  return <><AdminHeading title="Reports" subtitle="Appointment activity, sources, and service demand." action={<a className="button" href={`/api/admin/reports/export?${queryString(filters)}`}>Export CSV</a>}/><div className="card"><Filters filters={filters} setFilters={setFilters}/></div><ErrorBox error={query.error}/>{query.isPending?<Loading/>:query.data&&<><div className="stats-grid"><div className="stat-card"><div><span>Total appointments</span><strong>{query.data.total}</strong></div></div><div className="stat-card"><div><span>Cancellation rate</span><strong>{query.data.total?Math.round((query.data.statuses.cancelled||0)/query.data.total*100):0}%</strong></div></div><div className="stat-card"><div><span>No-show rate</span><strong>{query.data.total?Math.round((query.data.statuses.no_show||0)/query.data.total*100):0}%</strong></div></div></div><div className="admin-bottom-grid">{(['days','statuses','services','sources','hours'] as const).map(key=><div className="card" key={key}><h2>{({days:'Daily trend',statuses:'Visit status',services:'Popular services',sources:'Booking sources',hours:'Busiest hours (IST)'})[key]}</h2>{!Object.keys(query.data![key]).length?<Empty>No data for this period.</Empty>:<div className="bar-chart">{Object.entries(query.data![key]).sort().map(([name,count])=><div key={name}><div><span>{label(name)}</span><strong>{count}</strong></div><div className="bar-track"><span style={{width:`${count/Math.max(...Object.values(query.data![key]))*100}%`}}/></div></div>)}</div>}</div>)}<div className="card"><h2>Enquiry pipeline (all time)</h2>{query.data.enquiries.map(e=><p key={e.status}>{label(e.status)}: <strong>{e.total}</strong></p>)}</div></div><button className="button secondary no-print" onClick={()=>window.print()}>Print report</button></>}</>
}
export function ReadOnlyPage({kind}:{kind:'patients'|'audit'|'notifications'}) {
  const [page,setPage]=useState(1);const [error,setError]=useState<unknown>();const cache=useQueryClient();const user=useStaff();const allowed=kind==='patients'?user.role!=='doctor':user.role==='admin';const query=useQuery({queryKey:['admin',kind,page],queryFn:()=>api<Paginated<Row>>(`/admin/${kind}?page=${page}`),enabled:allowed})
  if(!allowed)return <Empty>This section is not available for your role.</Empty>
  const fields=kind==='patients'?['name','phone','age_group']:kind==='audit'?['created_at','actor_id','action','entity','entity_id']:['appointment_id','template','channel','recipient_mask','status','attempts','provider_response']
  return <><AdminHeading title={label(kind==='audit'?'audit_log':kind)} subtitle={kind==='notifications'?'Track queued updates and delivery attempts. SMS and WhatsApp require provider setup.':kind==='audit'?'A record of privileged actions and appointment changes.':'Minimal patient contact details from appointment requests.'}/><ErrorBox error={query.error||error}/>{query.isPending?<Loading/>:<div className="card"><div className="table-scroll"><table><thead><tr>{fields.map(f=><th key={f}>{label(f)}</th>)}{kind==='notifications'&&<th>Action</th>}</tr></thead><tbody>{query.data?.data.map(row=><tr key={String(row.id)}>{fields.map(f=><td key={f}>{String(row[f]??'—')}</td>)}{kind==='notifications'&&<td>{['failed','unconfigured'].includes(String(row.status))&&<button className="text-link" onClick={async()=>{try{await api(`/admin/notifications/${row.id}/retry`,'POST');cache.invalidateQueries({queryKey:['admin',kind]})}catch(e){setError(e)}}}>Retry</button>}</td>}</tr>)}</tbody></table></div>{!query.data?.data.length&&<Empty>No records yet.</Empty>}<Pagination page={page} last={query.data?.last_page||1} setPage={setPage}/></div>}</>
}
export function ClinicSettings() {
  const user=useStaff();const query=useQuery({queryKey:['admin','settings'],queryFn:()=>api<Record<string,Row>>('/admin/settings'),enabled:user.role==='admin'});const [form,setForm]=useState<Record<string,Row>|null>(null);const [error,setError]=useState<unknown>();const [saved,setSaved]=useState(false);const [busy,setBusy]=useState(false);const cache=useQueryClient();const data=form||query.data
  const fields:Field[]=[...['name','name_hi','doctor','doctor_hi','qualifications','designation','address','address_hi','phone','whatsapp','email','map_url','registration'].map(key=>({key,label:label(key),required:['name','doctor','address'].includes(key)})),{key:'consent_text',label:'Booking consent text',type:'textarea',required:true},{key:'instructions',label:'Confirmation instructions',type:'textarea',required:true},{key:'hours_confirmed',label:'Clinic hours have been confirmed',type:'checkbox'},{key:'services_confirmed',label:'Services have been confirmed',type:'checkbox'}]
  if(user.role!=='admin')return <Empty>Settings are available to administrators.</Empty>
  return <><AdminHeading title="Clinic settings" subtitle="Your public profile, booking policies, and message templates."/><BrandingSettings/><ErrorBox error={query.error||error}/>{query.isPending?<Loading/>:data&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setSaved(false);try{await api('/admin/settings','PUT',data);cache.invalidateQueries();setSaved(true)}catch(err){setError(err)}finally{setBusy(false)}}}><div className="admin-bottom-grid"><div className="card"><h2>Clinic profile</h2>{fields.map(field=><DynamicField key={field.key} field={field} value={data.clinic[field.key]} set={v=>setForm({...data,clinic:{...data.clinic,[field.key]:v}})}/>)}</div><div><div className="card"><h2>Booking policy</h2>{([{key:'instant_confirmation',label:'Confirm bookings instantly',type:'checkbox'},...['horizon_days','lead_minutes','cutoff_hours','daily_capacity'].map(key=>({key,label:label(key),type:'number',required:true}))] as Field[]).map(field=><DynamicField key={field.key} field={field} value={data.booking[field.key]} set={v=>setForm({...data,booking:{...data.booking,[field.key]:v}})}/>)}<label>Reminder hours before appointment<input value={(data.booking.reminder_hours as number[]).join(',')} onChange={e=>setForm({...data,booking:{...data.booking,reminder_hours:e.target.value.split(',').filter(Boolean).map(Number)}})}/><small>Comma-separated hours, e.g. 24,2</small></label></div><div className="card"><h2>Notification templates</h2><p className="small-text">Available placeholders: {'{reference}, {status}, {time}'}. Do not include clinical details.</p>{Object.entries(data.templates||{}).map(([key,value])=><label key={key}>{label(key)}<textarea rows={3} value={String(value)} onChange={e=>setForm({...data,templates:{...data.templates,[key]:e.target.value}})}/></label>)}</div></div></div>{saved&&<p className="success" role="status">Settings saved.</p>}<button className="button" disabled={busy}>{busy?'Saving…':'Save settings'}</button></form>}</>
}
export function MediaLibrary() {
  const user=useStaff();const query=useQuery({queryKey:['admin','media'],queryFn:()=>api<GalleryImage[]>('/admin/media'),enabled:user.role==='admin'});const cache=useQueryClient();const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false)
  if(user.role!=='admin')return <Empty>Media is available to administrators.</Empty>
  return <><AdminHeading title="Media library" subtitle="Upload clinic photographs and select Publish to display them on the website. Click any image to open the viewer."/><ErrorBox error={error||query.error}/><form className="card" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);data.set('published',data.has('published')?'1':'0');setBusy(true);setError(null);try{await api('/admin/media','POST',data);cache.invalidateQueries();form.reset()}catch(err){setError(err)}finally{setBusy(false)}}}><div className="form-grid"><label>Image (JPG, PNG, WebP; up to 4 MB)<input name="image" type="file" accept="image/jpeg,image/png,image/webp" required/></label><label>Descriptive alt text<input name="alt" required maxLength={200}/></label><label>Caption<input name="caption" maxLength={200}/></label><label className="checkbox"><input name="published" type="checkbox"/>Publish in clinic gallery</label></div><button className="button" disabled={busy}>{busy?'Uploading…':'Upload image'}</button></form>{query.isPending?<Loading/>:query.data?.length?<GalleryGrid images={query.data} actions={m=><><Badge status={m.published?'published':'draft'}/><button className="text-link" disabled={busy} onClick={async()=>{setBusy(true);setError(null);try{await api(`/admin/media/${m.id}`,'PUT',{alt:m.alt,caption:m.caption,published:!m.published});await cache.invalidateQueries()}catch(e){setError(e)}finally{setBusy(false)}}}>{m.published?'Unpublish':'Publish'}</button></>}/>:<Empty>No gallery images yet. Upload your first clinic photograph above.</Empty>}</>
}
