import { useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useForm, useWatch } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { ArrowLeft, ArrowRight, CalendarDays, Check, Copy, Download, LockKeyhole, MapPin } from 'lucide-react'
import { addDays, api, ApiError, dateText, timeText, today, useClinic, useServices } from './lib'
import type { Summary } from './lib'
import { Badge, Empty, ErrorBox, Loading, PageTitle, Seo } from './components'

const bookingSchema=z.object({name:z.string().trim().min(2,'Enter your full name.').max(100),phone:z.string().regex(/^[6-9][0-9]{9}$/,'Enter a valid 10-digit Indian mobile number.'),age_group:z.string().min(1,'Select an age group.'),gender:z.string(),reason:z.string().max(500),follow_up:z.boolean(),consent:z.boolean().refine(v=>v,'Please accept the privacy notice to continue.'),communication:z.enum(['none','email']),email:z.string(),website:z.string(),source:z.enum(['phone','walk_in'])}).refine(v=>v.communication!=='email'||z.email().safeParse(v.email).success,{path:['email'],message:'Enter a valid email for updates.'})
type BookingValues=z.infer<typeof bookingSchema>
export function SlotPicker({serviceId,date,setDate,value,onChange}:{serviceId:number;date:string;setDate:(date:string)=>void;value:string;onChange:(value:string)=>void}) {
  const clinic=useClinic();const slots=useQuery({queryKey:['slots',serviceId,date],queryFn:()=>api<{slots:{starts_at:string;label:string;remaining:number}[]}>(`/public/availability?service_id=${serviceId}&date=${date}`),enabled:!!serviceId&&!!date,staleTime:0})
  return <><label>Preferred date<input type="date" value={date} min={today()} max={addDays(today(),clinic.data?.booking.horizon_days||30)} onChange={e=>{setDate(e.target.value);onChange('')}}/></label><div className="slot-header"><strong>Available times</strong><small>India Standard Time (IST)</small></div><ErrorBox error={slots.error}/>{!serviceId?<Empty>Select a consultation to see available times.</Empty>:slots.isPending?<Loading/>:slots.data?.slots.length?<div className="slots" role="group" aria-label="Available appointment times">{slots.data.slots.map(s=><button type="button" className={value===s.starts_at?'selected':''} aria-pressed={value===s.starts_at} key={s.starts_at} onClick={()=>onChange(s.starts_at)}>{s.label}</button>)}</div>:<Empty>No times available on this date. Please choose another day.</Empty>}</>
}
export function Booking({staff=false}:{staff?:boolean}) {
  const [params]=useSearchParams();const navigate=useNavigate();const cache=useQueryClient();const clinic=useClinic();const services=useServices();const [step,setStep]=useState(1);const [serviceId,setServiceId]=useState(Number(params.get('service'))||0);const [date,setDate]=useState(addDays(today(),1));const [slot,setSlot]=useState('');const [error,setError]=useState<unknown>();const [staffResult,setStaffResult]=useState<{appointment:Summary;token:string}|null>(null)
  const {register,handleSubmit,control,setError:fieldError,formState:{errors,isSubmitting}}=useForm<BookingValues>({resolver:zodResolver(bookingSchema),defaultValues:{name:'',phone:'',age_group:'',gender:'prefer_not',reason:'',follow_up:false,consent:false,communication:'none',email:'',website:'',source:'phone'}})
  const values=useWatch({control}) as BookingValues
  const selected=services.data?.find(s=>s.id===serviceId)
  async function submit(values:BookingValues) {
    try {setError(null);const result=await api<{appointment:Summary;token:string}>(staff?'/admin/appointments':'/public/appointments','POST',{...values,email:values.email||null,service_id:serviceId,starts_at:slot});cache.invalidateQueries({queryKey:['slots']});if(staff){setStaffResult(result);cache.invalidateQueries({queryKey:['admin']})}else navigate(`/manage#${result.token}`,{replace:true})}
    catch(e){setError(e);if(e instanceof ApiError){Object.entries(e.errors).forEach(([key,value])=>fieldError(key as keyof BookingValues,{message:value[0]}));if(e.errors.starts_at){setStep(1);setSlot('');cache.invalidateQueries({queryKey:['slots']})}}}
  }
  if(staffResult)return <div className="card"><h2>Appointment created</h2><p>{staffResult.appointment.reference}</p><Badge status={staffResult.appointment.status}/><p>Give the patient this private management link:</p><input readOnly aria-label="Patient management link" value={`${location.origin}/manage#${staffResult.token}`}/><Link to="/admin/appointments" className="button">Return to appointments</Link></div>
  return <div className={staff?'':'container section'}><Seo title="Book an appointment" noindex={staff}/><PageTitle eyebrow={staff?'RECEPTION':'LET’S PLAN YOUR VISIT'} title={staff?'Create an appointment':'A little time for your health.'}>Choose a convenient time. We’ll take it from here.</PageTitle><div className="booking-grid"><div className="card booking-card"><ol className="stepper" aria-label="Booking progress">{['Your visit','Your details','Review'].map((text,i)=><li key={text} className={step>=i+1?'current':''} aria-current={step===i+1?'step':undefined}><span>{step>i+1?<Check size={15}/>:i+1}</span>{text}</li>)}</ol><ErrorBox error={error}/><ErrorBox error={clinic.error||services.error}/>
    <form onSubmit={handleSubmit(submit)}>{step===1&&<><h2>When would you like to visit?</h2><label>Consultation<select value={serviceId||''} onChange={e=>{setServiceId(Number(e.target.value));setSlot('')}}><option value="">Select a consultation</option>{services.data?.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><SlotPicker serviceId={serviceId} date={date} setDate={setDate} value={slot} onChange={setSlot}/>{!clinic.data?.profile.hours_confirmed&&<p className="notice">Booking hours are provisional. Reception will confirm your visit.</p>}<div className="form-actions"><button type="button" className="button" disabled={!slot||!selected} onClick={()=>setStep(2)}>Continue <ArrowRight size={18}/></button></div></>}
    <div hidden={step!==2}><h2>A few details about you.</h2><div className="form-grid"><label>Patient’s full name<input autoComplete="name" {...register('name')}/>{errors.name&&<small className="field-error">{errors.name.message}</small>}</label><label>Mobile number<input inputMode="tel" autoComplete="tel" maxLength={10} {...register('phone')}/>{errors.phone&&<small className="field-error">{errors.phone.message}</small>}</label><label>Age group<select {...register('age_group')}><option value="">Select age group</option><option value="under_18">Under 18</option><option value="18_35">18–35</option><option value="36_60">36–60</option><option value="over_60">Over 60</option></select>{errors.age_group&&<small className="field-error">{errors.age_group.message}</small>}</label><label>Gender (optional)<select {...register('gender')}><option value="prefer_not">Prefer not to say</option><option value="female">Female</option><option value="male">Male</option><option value="other">Other</option></select></label></div><label>What would you like to discuss? (optional)<textarea rows={3} maxLength={500} {...register('reason')} placeholder="A brief reason for your visit is enough."/>{errors.reason&&<small className="field-error">{errors.reason.message}</small>}</label><label className="checkbox"><input type="checkbox" {...register('follow_up')}/>This is a follow-up visit</label><label>Appointment updates<select {...register('communication')}><option value="none">No email updates</option><option value="email">Email me appointment updates</option></select></label>{values.communication==='email'&&<label>Email address<input type="email" autoComplete="email" {...register('email')}/>{errors.email&&<small className="field-error">{errors.email.message}</small>}</label>}{staff&&<label>Booking source<select {...register('source')}><option value="phone">Phone</option><option value="walk_in">Walk-in</option></select></label>}<input className="honeypot" tabIndex={-1} autoComplete="off" aria-hidden="true" {...register('website')}/><div className="form-actions"><button type="button" className="button secondary" onClick={()=>setStep(1)}><ArrowLeft size={16}/>Back</button><button type="button" className="button" onClick={()=>{const v=values;const result=bookingSchema.safeParse({...v,consent:true});if(result.success)setStep(3);else result.error.issues.forEach(i=>fieldError(i.path[0] as keyof BookingValues,{message:i.message}))}}>Review appointment <ArrowRight size={17}/></button></div></div>
    {step===3&&<><h2>Everything look right?</h2><dl className="review-list"><div><dt>Patient</dt><dd>{values.name}</dd></div><div><dt>Mobile</dt><dd>{values.phone}</dd></div><div><dt>Consultation</dt><dd>{selected?.name}</dd></div><div><dt>When</dt><dd>{dateText(slot)} · {timeText(slot)} IST</dd></div><div><dt>Visit</dt><dd>{values.follow_up?'Follow-up':'New visit'}</dd></div></dl><label className="checkbox"><input type="checkbox" {...register('consent')}/><span>{clinic.data?.profile.consent_text} <Link to="/privacy" target="_blank">Privacy notice</Link></span></label>{errors.consent&&<small className="field-error">{errors.consent.message}</small>}<div className="form-actions"><button type="button" className="button secondary" onClick={()=>setStep(2)}>Back</button><button type="submit" className="button" disabled={isSubmitting}>{isSubmitting?'Booking…':'Request appointment'}<Check size={18}/></button></div></>}
    </form></div><aside className="booking-aside"><span className="icon-tile"><CalendarDays/></span><h3>Your visit at a glance</h3><p><strong>{clinic.data?.profile.doctor}</strong><br/>{clinic.data?.profile.qualifications}</p><hr/><p><MapPin size={16}/> {clinic.data?.profile.address}</p>{selected&&<p>{selected.name}</p>}{slot&&<p><strong>{dateText(slot)}<br/>{timeText(slot)} IST</strong></p>}<hr/><p className="small-text"><LockKeyhole size={16}/> Your details are used to arrange your visit.</p><p className="small-text">You can change your booking up to {clinic.data?.booking.cutoff_hours??2} hours before your visit.</p><p className="small-text">For appointments only. This website is not an emergency service.</p></aside></div></div>
}
export function ManageBooking() {
  const params=useParams();const token=params.token||location.hash.slice(1);const clinic=useClinic();const cache=useQueryClient();const booking=useQuery({queryKey:['booking',token],queryFn:()=>api<Summary>(`/public/appointments/${token}`),enabled:!!token,retry:false});const [mode,setMode]=useState('');const [date,setDate]=useState(addDays(today(),1));const [slot,setSlot]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>();const [copied,setCopied]=useState(false)
  async function change(data:unknown){setBusy(true);try{setError(null);await api(`/public/appointments/${token}`,'PATCH',data);await cache.invalidateQueries({queryKey:['booking',token]});cache.invalidateQueries({queryKey:['slots']});setMode('')}catch(e){setError(e)}finally{setBusy(false)}}
  function calendar(a:Summary){const stamp=(v:string)=>new Date(v).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const text=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Nav Jeevan//Appointments//EN\r\nBEGIN:VEVENT\r\nUID:${a.reference}@navjeevan\r\nDTSTAMP:${stamp(new Date().toISOString())}\r\nDTSTART:${stamp(a.starts_at)}\r\nDTEND:${stamp(a.ends_at)}\r\nSUMMARY:Clinic appointment ${a.reference}\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/calendar'}));const link=document.createElement('a');link.href=url;link.download=`${a.reference}.ics`;link.click();URL.revokeObjectURL(url)}
  const a=booking.data
  return <div className="container section narrow"><Seo title="Your appointment" noindex/><PageTitle eyebrow="YOUR PRIVATE BOOKING PAGE" title={a?.status==='cancelled'?'Appointment cancelled':'Your appointment details.'}/>{!token?<Empty>Open the private link from your booking confirmation to manage your visit.</Empty>:booking.isPending?<Loading/>:booking.error?<ErrorBox error={booking.error}/>:a&&<div className="card"><div className="confirmation-top"><span className="icon-tile"><Check/></span><Badge status={a.status}/></div><h2>{a.reference}</h2><p>{a.status==='pending'?'Your request has been received. Reception will review it.':'The current status of your visit is shown above.'}</p><dl className="review-list"><div><dt>Patient</dt><dd>{a.patient_name} · {a.phone_mask}</dd></div><div><dt>Consultation</dt><dd>{a.service}</dd></div><div><dt>Date & time</dt><dd>{dateText(a.starts_at)} · {timeText(a.starts_at)} IST</dd></div><div><dt>Clinic</dt><dd>{clinic.data?.profile.address}</dd></div></dl><p>{clinic.data?.profile.instructions}</p><div className="notice"><strong>Save this private link.</strong> Anyone with it can access and change this booking. It expires two days after your visit.</div><div className="form-actions wrap"><button className="button secondary" onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setCopied(true)}catch{setError(new Error('Copy the URL from your browser address bar.'))}}}><Copy size={16}/>{copied?'Copied':'Copy private link'}</button>{a.status!=='cancelled'&&<button className="button secondary" onClick={()=>calendar(a)}><Download size={16}/>Add to calendar</button>}</div><ErrorBox error={error}/>{a.can_manage&&<><div className="form-actions"><button className="text-link" onClick={()=>setMode('reschedule')}>Reschedule</button><button className="text-link danger" onClick={()=>setMode('cancel')}>Cancel appointment</button></div>{mode==='cancel'&&<div className="notice"><p>Cancel this appointment and release the time for another patient?</p><button className="button danger-button" disabled={busy} onClick={()=>change({status:'cancelled'})}>{busy?'Cancelling…':'Yes, cancel appointment'}</button><button className="button secondary" onClick={()=>setMode('')}>Keep appointment</button></div>}{mode==='reschedule'&&<div><SlotPicker serviceId={a.service_id} date={date} setDate={setDate} value={slot} onChange={setSlot}/><button className="button" disabled={!slot||busy} onClick={()=>change({starts_at:slot})}>{busy?'Saving…':'Confirm new time'}</button></div>}</>}{!a.can_manage&&a.status!=='cancelled'&&<p className="notice">Online changes are closed. Please contact reception for help.</p>}</div>}<p className="small-text">Not an emergency service. For urgent care, seek immediate in-person assistance.</p></div>
}
