import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, ArrowRight, BookOpen, Clock3, Search, Stethoscope } from 'lucide-react'
import { useContent, useServices } from './lib'
import type { Page, Service } from './lib'
import { Empty, ErrorBox, Loading, PageTitle, Seo } from './components'

const minutes=(body:string)=>Math.max(1,Math.ceil(body.trim().split(/\s+/).length/200))
export function ReadingText({text}:{text:string}){return <div className="reading-text">{text.split(/\n\s*\n/).filter(Boolean).map((paragraph,i)=><p key={i}>{paragraph}</p>)}</div>}
function ServiceCard({service:s}:{service:Service}){return <article className="care-card">{s.image_url&&<Link to={`/services/${s.slug}`} tabIndex={-1} aria-hidden="true"><img className="service-cover" src={s.image_url} alt="" loading="lazy"/></Link>}<div className="care-card-top"><span className="icon-tile"><Stethoscope size={25}/></span><span className="reading-meta"><Clock3 size={15}/>{s.duration} min appointment</span></div><h2><Link to={`/services/${s.slug}`}>{s.name}</Link></h2><p>{s.summary}</p><div className="care-card-bottom"><Link className="text-link" to={`/services/${s.slug}`}>Explore service <ArrowRight size={17}/></Link><Link className="button small" to={`/appointment?service=${s.id}`}>Book a visit</Link></div></article>}
function SearchBox({value,onChange,label}:{value:string;onChange:(value:string)=>void;label:string}){return <label className="care-search"><Search size={20}/><span className="sr-only">{label}</span><input type="search" value={value} onChange={e=>onChange(e.target.value)} placeholder={label}/></label>}
export function Services(){const {data,isPending,error}=useServices();const [search,setSearch]=useState('');const items=data?.filter(s=>`${s.name} ${s.summary}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()))||[];return <div className="container section care-page"><Seo title="Our services"/><PageTitle eyebrow="CARE AT NAV JEEVAN" title="Find the right care for your visit.">Explore our consultation options, understand what to expect, and choose a convenient appointment.</PageTitle><div className="care-toolbar"><SearchBox value={search} onChange={setSearch} label="Search services"/><span aria-live="polite">{items.length} service{items.length===1?'':'s'}</span></div>{isPending?<Loading/>:error?<ErrorBox error={error}/>:items.length?<div className="care-card-grid">{items.map(s=><ServiceCard key={s.id} service={s}/>)}</div>:<Empty>{search?'No services match your search. Try another name.':'Service information will be available soon.'}{search&&<button className="text-link" onClick={()=>setSearch('')}>Clear search</button>}</Empty>}<div className="care-help"><div><h2>Need help choosing a service?</h2><p>Contact reception to discuss your visit and the available consultation options.</p></div><Link className="button secondary" to="/contact">Contact the clinic <ArrowRight size={18}/></Link></div></div>}
export function ServiceDetail(){const {slug}=useParams();const {data,isPending,error}=useServices();if(isPending)return <Loading/>;if(error)return <ErrorBox error={error}/>;const s=data?.find(item=>item.slug===slug);if(!s)return <Missing/>;return <div className="container section care-page"><Seo title={s.seo_title||s.name} description={s.seo_description||s.summary}/><Link className="text-link care-back" to="/services"><ArrowLeft size={16}/>All services</Link><PageTitle eyebrow="CONSULTATION" title={s.name}>{s.summary}</PageTitle><div className="care-detail-grid"><div>{s.image_url&&<img className="care-detail-cover" src={s.image_url} alt={s.image_alt||s.name}/>}<section className="care-panel"><h2>About this service</h2><ReadingText text={s.description||s.summary}/></section>{s.preparation&&<section className="care-panel"><h2>Before your visit</h2><ReadingText text={s.preparation}/></section>}</div><aside className="care-booking"><span className="icon-tile"><Stethoscope/></span><h2>Plan your consultation</h2><p className="reading-meta"><Clock3 size={18}/>{s.duration} minute appointment slot</p><p>Consultation times may vary. Select an available time to request your visit.</p><Link className="button full" to={`/appointment?service=${s.id}`}>Book this service <ArrowRight size={18}/></Link><Link className="text-link" to="/contact">Ask reception a question</Link></aside></div>{!!data?.filter(item=>item.id!==s.id).length&&<section className="care-related"><h2>Explore other services</h2><div className="care-card-grid">{data.filter(item=>item.id!==s.id).slice(0,2).map(item=><ServiceCard key={item.id} service={item}/>)}</div></section>}</div>}
function ArticleCard({page,featured=false}:{page:Page;featured?:boolean}){return <article className={`journal-card${featured?' journal-featured':''}`} lang={page.language}>{page.image_url?<img className="journal-cover" src={page.image_url} alt={page.image_alt||page.title} loading="lazy"/>:<div className="journal-art" aria-hidden="true"><BookOpen size={featured?60:38}/><span>NAV JEEVAN JOURNAL</span></div>}<div className="journal-copy"><div className="reading-meta"><span>{page.language==='hi'?'हिन्दी':'English'}</span><span>·</span><Clock3 size={14}/><span>{minutes(page.body)} min read</span></div><h2><Link to={`/articles/${page.slug}`}>{page.title}</Link></h2><p>{page.excerpt}</p><Link className="text-link" to={`/articles/${page.slug}`}>Read article <ArrowRight size={17}/></Link></div></article>}
export function Articles(){const {data,isPending,error}=useContent();const [search,setSearch]=useState('');const [language,setLanguage]=useState('all');const all=data?.filter(p=>p.type==='article')||[];const items=all.filter(p=>(language==='all'||p.language===language)&&`${p.title} ${p.excerpt} ${p.body}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));return <div className="container section care-page"><Seo title="Health articles"/><PageTitle eyebrow="THE NAV JEEVAN JOURNAL" title="Make room for understanding.">Explore health articles and updates from the clinic, in English and Hindi.</PageTitle><div className="care-toolbar"><SearchBox value={search} onChange={setSearch} label="Search health articles"/><label className="journal-language">Language<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="all">All languages</option><option value="en">English</option><option value="hi">हिन्दी</option></select></label><span aria-live="polite">{items.length} article{items.length===1?'':'s'}</span></div>{isPending?<Loading/>:error?<ErrorBox error={error}/>:items.length?<><ArticleCard page={items[0]} featured/><div className="care-card-grid journal-grid">{items.slice(1).map(p=><ArticleCard page={p} key={p.id}/>)}</div></>:<Empty>{all.length?'No articles match these filters.':'Our first articles are on their way. Please check back soon.'}{(search||language!=='all')&&<button className="text-link" onClick={()=>{setSearch('');setLanguage('all')}}>Clear filters</button>}</Empty>}</div>}
export function ContentDetail({slug:fixed}:{slug?:string}){const {slug}=useParams();const {data,isPending,error}=useContent();if(isPending)return <Loading/>;if(error)return <ErrorBox error={error}/>;const page=data?.find(p=>p.slug===(fixed||slug));if(!page)return <Missing/>;const isArticle=page.type==='article';const related=data?.filter(p=>p.type==='article'&&p.id!==page.id&&p.language===page.language).slice(0,2)||[];return <div className="container section care-page"><Seo title={page.seo_title||page.title} description={page.seo_description||page.excerpt}/>{isArticle&&<Link className="text-link care-back" to="/articles"><ArrowLeft size={16}/>All health articles</Link>}<article className="journal-reading" lang={page.language}><PageTitle eyebrow={isArticle?'NAV JEEVAN JOURNAL':'PATIENT INFORMATION'} title={page.title}>{page.excerpt}</PageTitle>{isArticle&&<div className="reading-meta journal-byline"><BookOpen size={17}/><span>{page.language==='hi'?'हिन्दी':'English'}</span><span>·</span><span>{minutes(page.body)} min read</span></div>}{page.image_url&&<img className="care-detail-cover" src={page.image_url} alt={page.image_alt||page.title}/>}<ReadingText text={page.body}/>{isArticle&&<div className="journal-end"><BookOpen size={20}/><Link className="text-link" to="/articles">Explore more health articles <ArrowRight size={16}/></Link></div>}</article>{isArticle&&related.length>0&&<section className="care-related"><h2>Continue reading</h2><div className="care-card-grid">{related.map(p=><ArticleCard key={p.id} page={p}/>)}</div></section>}</div>}
function Missing(){return <div className="container section"><PageTitle title="Page not found" eyebrow="NAV JEEVAN">This content is not available.</PageTitle><Link className="button" to="/">Back to home</Link></div>}
