import { useEffect } from 'react'
import { BrowserRouter, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { About, Articles, Contact, ContentDetail, FaqSection, Home, NotFound, PublicLayout, ServiceDetail, Services } from './PublicSite'
import { useClinic } from './lib'
import { Booking, ManageBooking } from './Booking'
import { AdminLayout, AppointmentDetail, Appointments, ClinicSettings, Dashboard, Login, MediaLibrary, ReadOnlyPage, Reports, ResourcePage } from './Admin'
const client=new QueryClient({defaultOptions:{queries:{staleTime:30000,retry:1,refetchOnWindowFocus:false}}})
function ScrollReset(){const {pathname}=useLocation();const navigate=useNavigate();const clinic=useClinic();useEffect(()=>{window.scrollTo(0,0);const redirect=clinic.data?.redirects?.find(r=>r.from_path===pathname);if(redirect)navigate(redirect.to_path,{replace:true})},[pathname,clinic.data,navigate]);return null}
export default function ClinicApp(){return <QueryClientProvider client={client}><BrowserRouter><ScrollReset/><Routes><Route element={<PublicLayout/>}><Route index element={<Home/>}/><Route path="about" element={<About/>}/><Route path="doctor" element={<About/>}/><Route path="services" element={<Services/>}/><Route path="services/:slug" element={<ServiceDetail/>}/><Route path="articles" element={<Articles/>}/><Route path="pages/:slug" element={<ContentDetail/>}/><Route path="articles/:slug" element={<ContentDetail/>}/><Route path="faqs" element={<FaqSection/>}/><Route path="contact" element={<Contact/>}/><Route path="privacy" element={<ContentDetail slug="privacy"/>}/><Route path="terms" element={<ContentDetail slug="terms"/>}/><Route path="disclaimer" element={<ContentDetail slug="disclaimer"/>}/><Route path="appointment" element={<Booking/>}/><Route path="manage" element={<ManageBooking/>}/><Route path="manage/:token" element={<ManageBooking/>}/><Route path="*" element={<NotFound/>}/></Route><Route path="login" element={<Login/>}/><Route path="admin" element={<AdminLayout/>}><Route index element={<Dashboard/>}/><Route path="appointments" element={<Appointments/>}/><Route path="appointments/:id" element={<AppointmentDetail/>}/><Route path="book" element={<Booking staff/>}/><Route path="patients" element={<ReadOnlyPage kind="patients"/>}/><Route path="audit" element={<ReadOnlyPage kind="audit"/>}/><Route path="notifications" element={<ReadOnlyPage kind="notifications"/>}/><Route path="reports" element={<Reports/>}/><Route path="settings" element={<ClinicSettings/>}/><Route path="media" element={<MediaLibrary/>}/><Route path=":resource" element={<ResourcePage key={location.pathname}/>}/></Route></Routes></BrowserRouter></QueryClientProvider>}
