import { useState } from 'react'
import { Link, NavLink, Outlet, useParams } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronDown, Clock3, Heart, HeartPulse, MapPin, Menu, MessageCircle, Phone, ShieldCheck, Stethoscope, X } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { api, useClinic, useContent, useServices } from './lib'
import { BookLink, Empty, ErrorBox, Loading, Logo, PageTitle, Seo } from './components'

export function PublicLayout() {
  const {data}=useClinic(); const p=data?.profile; const [open,setOpen]=useState(false)
  return <><a className="skip-link" href="#main">Skip to content</a><div className="utility"><div className="container"><span><MapPin size={13}/>{p?.address||'Singarjot Ghat, Mahuadhani'}</span><span>For appointments, not emergencies {p?.phone&&<a href={`tel:${p.phone}`}><Phone size={13}/>{p.phone}</a>}</span></div></div>
    <header className="site-header"><div className="container header-inner"><Logo/><button className="menu-toggle icon-button" onClick={()=>setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''} aria-label="Main navigation">{[['/','Home'],['/about','About us'],['/services','Our services'],['/articles','Health articles'],['/contact','Contact']].map(([to,name])=><NavLink key={to} to={to} end onClick={()=>setOpen(false)}>{name}</NavLink>)}<BookLink className="small"/></nav></div></header>
    <main id="main">{data?.banners?.map(b=><div className="container notice" key={b.id}><strong>{b.title}</strong><p>{b.body}</p>{b.link_path&&<Link className="text-link" to={b.link_path}>{b.link_label||'Learn more'} <ArrowUpRight size={16}/></Link>}</div>)}<Outlet/></main><footer><div className="container footer-grid"><div><Logo/><p>Care that begins with a conversation.<br/>आपके स्वास्थ्य की ओर एक कदम।</p><p className="muted">{p?.address}<br/>{p?.address_hi}</p></div><div><h3>Explore</h3><Link to="/about">The clinic & doctor</Link><Link to="/services">Our services</Link><Link to="/appointment">Book an appointment</Link><Link to="/faqs">Frequently asked questions</Link></div><div><h3>Get in touch</h3>{p?.phone?<a href={`tel:${p.phone}`}>{p.phone}</a>:<span>Phone details coming soon</span>}<Link to="/contact">Send an enquiry</Link>{p?.map_url&&<a href={p.map_url} target="_blank" rel="noreferrer">Get directions ↗</a>}<Link to="/admin">Staff sign in ↗</Link></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Nav Jeevan Chikitsalay</span><div><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/disclaimer">Medical disclaimer</Link></div></div></footer>
    <div className="mobile-actions"><BookLink/>{p?.phone&&<a href={`tel:${p.phone}`} aria-label="Call clinic"><Phone/></a>}{p?.whatsapp&&<a href={`https://wa.me/${p.whatsapp}`} aria-label="WhatsApp clinic"><MessageCircle/></a>}</div></>
}
export function Home() {
  const clinic=useClinic(); const services=useServices(); const p=clinic.data?.profile
  return <><Seo title="Thoughtful care, close to home"/><section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow"><span className="little-dot"/> YOUR NEIGHBOURHOOD CLINIC</span><h1>Thoughtful care.<br/><em>A healthier you.</em></h1><p>Take the next step towards better health with {p?.doctor||'Dr. Parmesh Kumar'} at Nav Jeevan Chikitsalay. Personal attention, a clear conversation, and care close to home.</p><div className="hero-actions"><BookLink/ ><Link to="/about" className="text-link">Meet your doctor <ArrowRight size={18}/></Link></div><div className="hero-note"><ShieldCheck size={19}/><span>No account needed · Simple appointment booking</span></div></div>
    <div className="hero-art" aria-label="Clinic and practitioner information"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="botanical leaf-one"/><div className="botanical leaf-two"/><div className="doctor-card"><div className="doctor-card-top"><span className="mini-label">NAV JEEVAN CHIKITSALAY</span><HeartPulse size={24}/></div><div className="doctor-emblem"><Stethoscope size={85} strokeWidth={1.1}/><span className="emblem-cross">+</span></div><span className="eyebrow">MEET YOUR DOCTOR</span><h2>{p?.doctor||'Dr. Parmesh Kumar'}</h2><p lang="hi">{p?.doctor_hi||'डॉ परमेश कुमार'}</p><span className="credentials">{p?.qualifications||'BAMS, DETCT'}</span><div className="doctor-card-foot">{p?.designation||'General Physician and Surgeon'}<ArrowUpRight size={19}/></div></div><div className="floating-note"><span className="icon-tile"><Heart size={21}/></span><div>Here to listen.<small>Here to care for you.</small></div></div><div className="art-caption">स्वस्थ जीवन की नई शुरुआत</div></div></div></section>
    <div className="container quick-strip"><div><MapPin/><span><small>FIND US</small>{p?.address||'Singarjot Ghat, Mahuadhani'}</span></div><div><Clock3/><span><small>CONSULTATION HOURS</small>{p?.hours_confirmed?'View weekly clinic timings':'Please confirm timings with reception'}</span></div><Link to="/appointment"><CalendarDays/><span><small>PLAN YOUR VISIT</small>Choose a convenient time</span><ArrowUpRight size={20}/></Link></div>
    <section className="section container"><div className="section-heading"><div><span className="eyebrow">CARE FOR EVERYDAY LIFE</span><h2>Let’s start with your health.</h2></div><Link className="text-link" to="/services">Explore services <ArrowRight size={18}/></Link></div>{services.isPending?<Loading/>:services.error?<ErrorBox error={services.error}/>:<div className="service-grid">{services.data?.map((s,i)=><Link to={`/services/${s.slug}`} className="service-card" key={s.id}><span className={`icon-tile tone-${i}`}><Stethoscope size={26}/></span><h3>{s.name}</h3><p>{s.summary}</p><span className="text-link">Learn more <ArrowUpRight size={17}/></span></Link>)}<div className="service-card help-card"><MessageCircle size={28}/><h3>Not sure where to start?</h3><p>Send reception an enquiry. We’ll help you plan your visit.</p><Link className="text-link" to="/contact">Talk to the clinic <ArrowUpRight size={17}/></Link></div></div>}{p&&!p.services_confirmed&&<p className="setup-note">Consultation options are provisional. Please confirm the service you need with reception.</p>}</section>
    <section className="care-section"><div className="container care-grid"><div><span className="eyebrow">A LITTLE CLOSER. A LITTLE MORE PERSONAL.</span><h2>Your health deserves<br/>time and attention.</h2><p>Visiting a clinic should feel straightforward. Find the information you need, request a time, and let us help you take the next step.</p><Link to="/about" className="text-link">Get to know us <ArrowRight size={18}/></Link></div><div className="care-points">{([[Heart,'A conversation first','Share your concerns directly with the doctor.'],[CalendarDays,'A simpler visit','Book online and keep your appointment details in one place.'],[MapPin,'Part of your neighbourhood','Find us at Singarjot Ghat, Mahuadhani.']] as const).map(([Icon,title,text])=><div className="care-point" key={String(title)}><span className="icon-tile"><Icon size={24}/></span><div><h3>{String(title)}</h3><p>{String(text)}</p></div></div>)}</div></div></section>
    <section className="section container"><div className="visit-grid"><div><span className="eyebrow">YOUR VISIT, MADE SIMPLE</span><h2>Three steps to your appointment.</h2><p>A little planning. One less thing to worry about.</p></div>{[['01','Choose your visit','Select your consultation and an available time.'],['02','Share a few details','Tell us your name and how to contact you.'],['03','Keep your confirmation','Save your reference and private booking link.']].map(([n,title,text])=><div className="visit-step" key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>
    {!!clinic.data?.testimonials.length&&<section className="section container"><span className="eyebrow">PATIENT EXPERIENCES</span><h2>From our community</h2><div className="service-grid">{clinic.data.testimonials.map(t=><blockquote className="card" key={t.id}><p>“{t.quote}”</p><cite>{t.name}</cite></blockquote>)}</div></section>}
    <section className="container cta-banner"><div><span className="eyebrow">WE’RE HERE FOR YOU</span><h2>Make time for your health.</h2><p>Request your next visit in just a few steps.</p></div><BookLink className="light"/></section><FaqSection limit={4}/></>
}
export function Services() { const {data,isPending,error}=useServices(); return <div className="container section"><Seo title="Our services"/><PageTitle eyebrow="CONSULTATIONS" title="Care starts with listening.">Explore consultation options and plan your visit.</PageTitle><ErrorBox error={error}/>{isPending?<Loading/>:<div className="service-grid">{data?.map(s=><Link className="service-card" key={s.id} to={`/services/${s.slug}`}><span className="icon-tile"><Stethoscope/></span><h2>{s.name}</h2><p>{s.summary}</p><span className="text-link">View consultation <ArrowRight size={17}/></span></Link>)}</div>}</div> }
export function ServiceDetail() { const {slug}=useParams(); const {data,isPending,error}=useServices(); const s=data?.find(s=>s.slug===slug); if(isPending)return <Loading/>;if(error)return <ErrorBox error={error}/>;if(!s)return <NotFound/>;return <div className="container section narrow"><Seo title={s.seo_title||s.name} description={s.seo_description||s.summary}/><Link to="/services" className="text-link">← All services</Link><PageTitle eyebrow="CONSULTATION" title={s.name}>{s.summary}</PageTitle><div className="card prose"><p>{s.description}</p><h2>Before your visit</h2><p>{s.preparation}</p><p>Allow approximately {s.duration} minutes for your appointment. Actual consultation time may vary.</p><Link to={`/appointment?service=${s.id}`} className="button">Book this consultation <ArrowUpRight size={18}/></Link></div></div> }
export function About() {const {data,isPending,error}=useClinic();if(isPending)return <Loading/>;if(error)return <ErrorBox error={error}/>;const p=data!.profile;return <div className="container section"><Seo title="About the clinic & doctor"/><PageTitle eyebrow="YOUR NEIGHBOURHOOD CLINIC" title="Welcome to Nav Jeevan.">नव जीवन चिकित्सालय — {p.address_hi}</PageTitle><div className="about-grid"><div className="about-portrait"><Stethoscope size={110} strokeWidth={1}/><span>नव जीवन चिकित्सालय</span></div><div className="prose"><span className="eyebrow">MEET YOUR DOCTOR</span><h2>{p.doctor}</h2><p lang="hi">{p.doctor_hi}</p><span className="credentials">{p.qualifications}</span><h3>{p.designation}</h3><p>Visit {p.name} at {p.address} for an in-person consultation. You can request an appointment online and manage your visit through your private booking link.</p>{p.registration&&<p>Registration: {p.registration}</p>}<BookLink/></div></div>{!!data!.media.length&&<div className="section"><h2>Around the clinic</h2><div className="service-grid">{data!.media.map(m=><figure key={m.id}><img src={m.path} alt={m.alt} loading="lazy"/><figcaption>{m.caption}</figcaption></figure>)}</div></div>}<div className="card section"><h2>Clinic timings</h2><Hours/></div></div>}
export function Hours() {const {data}=useClinic();if(!data)return null;return <>{!data.profile.hours_confirmed&&<p className="notice">These are provisional booking hours. Please confirm your visit with reception.</p>}<div className="hours">{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,i)=><div key={day}><span>{day}</span><strong>{data.hours.filter(h=>h.weekday===i).map(h=>`${h.start_time.slice(0,5)} – ${h.end_time.slice(0,5)}`).join(' / ')||'Closed'}</strong></div>)}</div><small>All times are in India Standard Time (IST).</small></>}
export function FaqSection({limit}:{limit?:number}) {const {data}=useContent();return <section className="section container faq-section"><div><span className="eyebrow">A FEW HELPFUL ANSWERS</span><h2>Before you visit.</h2><p>Have another question? <Link to="/contact">Get in touch.</Link></p></div><div>{data?.filter(p=>p.type==='faq').slice(0,limit).map(p=><details key={p.id}><summary>{p.title}<ChevronDown size={18}/></summary><p>{p.body}</p></details>)}</div></section>}
export function Articles() {const {data,isPending,error}=useContent();const articles=data?.filter(p=>p.type==='article');return <div className="container section"><Seo title="Health articles"/><PageTitle eyebrow="FROM THE CLINIC" title="A little more understanding.">Articles and clinic updates, reviewed before publication.</PageTitle><ErrorBox error={error}/>{isPending?<Loading/>:articles?.length?<div className="service-grid">{articles.map(p=><Link to={`/articles/${p.slug}`} className="service-card" key={p.id}><span className="eyebrow">CLINIC JOURNAL</span><h2>{p.title}</h2><p>{p.excerpt}</p><span className="text-link">Read article <ArrowRight size={18}/></span></Link>)}</div>:<Empty>Our first articles are on their way. Please check back soon.</Empty>}</div>}
export function ContentDetail({slug:fixed}:{slug?:string}) {const params=useParams();const {data,isPending,error}=useContent();if(isPending)return <Loading/>;if(error)return <ErrorBox error={error}/>;const page=data?.find(p=>p.slug===(fixed||params.slug));if(!page)return <NotFound/>;return <article className="container section narrow"><Seo title={page.seo_title||page.title} description={page.seo_description||page.excerpt}/><PageTitle eyebrow={page.type==='article'?'CLINIC JOURNAL':'PATIENT INFORMATION'} title={page.title}>{page.excerpt}</PageTitle><div className="card prose preserve-lines">{page.body}</div></article>}
export function Contact() {
  const {data}=useClinic();const p=data?.profile;const {register,handleSubmit,formState:{errors,isSubmitting},reset}=useForm<{name:string;phone:string;message:string;consent:boolean;website:string}>();const [error,setError]=useState<unknown>();const [sent,setSent]=useState(false)
  return <div className="container section"><Seo title="Contact & directions"/><PageTitle eyebrow="LET’S CONNECT" title="We’re closer than you think.">Find the clinic or send reception a message.</PageTitle><div className="contact-grid"><div><div className="location-card"><MapPin size={32}/><h2>Visit the clinic</h2><p>{p?.address}<br/>{p?.address_hi}</p>{p?.map_url&&<a className="button" href={p.map_url} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={18}/></a>}{p?.phone&&<p><a href={`tel:${p.phone}`}>{p.phone}</a></p>}{p?.whatsapp&&<a href={`https://wa.me/${p.whatsapp}`} className="text-link">Chat on WhatsApp <MessageCircle size={18}/></a>}</div><div className="card"><h3>Consultation hours</h3><Hours/></div></div><div className="card"><h2>Send an enquiry</h2><p>For appointment questions and clinic information. Please avoid sending medical records.</p>{sent?<div className="success" role="status"><Check/>Thank you. Reception will review your enquiry.<button className="text-link" onClick={()=>setSent(false)}>Send another</button></div>:<form onSubmit={handleSubmit(async values=>{try{setError(null);await api('/public/enquiries','POST',values);setSent(true);reset()}catch(e){setError(e)}})}><ErrorBox error={error}/><label>Your name<input {...register('name',{required:'Enter your name',minLength:2})} autoComplete="name"/>{errors.name&&<small className="field-error">Enter your name (at least 2 characters).</small>}</label><label>Mobile number<input {...register('phone',{required:true,pattern:/^[6-9][0-9]{9}$/})} inputMode="tel" autoComplete="tel" maxLength={10}/>{errors.phone&&<small className="field-error">Enter a valid 10-digit Indian mobile number.</small>}</label><label>Your message<textarea rows={5} {...register('message',{required:true,minLength:10,maxLength:1500})}/>{errors.message&&<small className="field-error">Use 10–1500 characters.</small>}</label><input className="honeypot" tabIndex={-1} aria-hidden="true" autoComplete="off" {...register('website')}/><label className="checkbox"><input type="checkbox" {...register('consent',{required:true})}/><span>I agree to the use of my details to answer this enquiry. <Link to="/privacy">Privacy notice</Link></span></label>{errors.consent&&<small className="field-error">Consent is required.</small>}<button className="button" disabled={isSubmitting}>{isSubmitting?'Sending…':'Send enquiry'}<ArrowUpRight size={18}/></button></form>}<p className="small-text">This form is not an emergency service.</p></div></div></div>
}
export function NotFound() {return <div className="container section narrow"><Seo title="Page not found" noindex/><PageTitle eyebrow="404" title="We couldn’t find that page."/><Link className="button" to="/">Back to home</Link></div>}
